
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace Assets.Scripts.MemoryPackObjects {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>UnityEngine.Vector3[]</b> Array<br/>
/// </code>
/// </remarks>
partial class Vector3ArrayValue : IMemoryPackable<Vector3ArrayValue>
{

    static partial void StaticConstructor();

    static Vector3ArrayValue()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Vector3ArrayValue>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new Vector3ArrayValueFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Vector3ArrayValue[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<Vector3ArrayValue>());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<global::UnityEngine.Vector3[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<global::UnityEngine.Vector3>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref Vector3ArrayValue? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteObjectHeader(1);
        writer.WriteUnmanagedArray(value.@Array);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref Vector3ArrayValue? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        global::UnityEngine.Vector3[] __Array;

        
        if (count == 1)
        {
            if (value == null)
            {
                __Array = reader.ReadUnmanagedArray<global::UnityEngine.Vector3>();


                goto NEW;
            }
            else
            {
                __Array = value.@Array;

                reader.ReadUnmanagedArray(ref __Array);

                goto SET;
            }

        }
        else if (count > 1)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(Vector3ArrayValue), 1, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __Array = default!;
            }
            else
            {
               __Array = value.@Array;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanagedArray(ref __Array); if (count == 1) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@Array = __Array;
        goto READ_END;

    NEW:
        value = new Vector3ArrayValue()
        {
            @Array = __Array
        };

    READ_END:

    END:

        return;
    }
}
partial class Vector3ArrayValue
{
    [global::MemoryPack.Internal.Preserve]
    sealed class Vector3ArrayValueFormatter : MemoryPackFormatter<Vector3ArrayValue>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref Vector3ArrayValue value)
        {
            Vector3ArrayValue.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref Vector3ArrayValue value)
        {
            Vector3ArrayValue.Deserialize(ref reader, ref value);
        }
    }
}
}
