
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;


/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>int</b> MyProperty<br/>
/// </code>
/// </remarks>
partial class GlobalNamespaceType : IMemoryPackable<GlobalNamespaceType>
{

    static partial void StaticConstructor();

    static GlobalNamespaceType()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<GlobalNamespaceType>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new GlobalNamespaceTypeFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<GlobalNamespaceType[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<GlobalNamespaceType>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref GlobalNamespaceType? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteUnmanagedWithObjectHeader(1, value.@MyProperty);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref GlobalNamespaceType? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        int __MyProperty;

        
        if (count == 1)
        {
            if (value == null)
            {
                reader.ReadUnmanaged(out __MyProperty);


                goto NEW;
            }
            else
            {
                __MyProperty = value.@MyProperty;

                reader.ReadUnmanaged(out __MyProperty);

                goto SET;
            }

        }
        else if (count > 1)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(GlobalNamespaceType), 1, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __MyProperty = default!;
            }
            else
            {
               __MyProperty = value.@MyProperty;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanaged(out __MyProperty); if (count == 1) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@MyProperty = __MyProperty;
        goto READ_END;

    NEW:
        value = new GlobalNamespaceType()
        {
            @MyProperty = __MyProperty
        };

    READ_END:

    END:

        return;
    }
}
partial class GlobalNamespaceType
{
    [global::MemoryPack.Internal.Preserve]
    sealed class GlobalNamespaceTypeFormatter : MemoryPackFormatter<GlobalNamespaceType>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref GlobalNamespaceType value)
        {
            GlobalNamespaceType.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref GlobalNamespaceType value)
        {
            GlobalNamespaceType.Deserialize(ref reader, ref value);
        }
    }
}
