
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>int</b> X<br/>
/// <b>string</b> Y<br/>
/// </code>
/// </remarks>
partial struct IncludesReferenceStruct : IMemoryPackable<IncludesReferenceStruct>
{

    static partial void StaticConstructor();

    static IncludesReferenceStruct()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<IncludesReferenceStruct>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new IncludesReferenceStructFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<IncludesReferenceStruct[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<IncludesReferenceStruct>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref IncludesReferenceStruct value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {



        writer.WriteUnmanagedWithObjectHeader(2, value.@X);
        writer.WriteString(value.@Y);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref IncludesReferenceStruct value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        int __X;
        string __Y;

        
        if (count == 2)
        {
            
            {
                reader.ReadUnmanaged(out __X);
                __Y = reader.ReadString();


                goto NEW;
            }
#if false
            {
                __X = value.@X;
                __Y = value.@Y;

                reader.ReadUnmanaged(out __X);
                __Y = reader.ReadString();

                goto SET;
            }
#endif
        }
        else if (count > 2)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(IncludesReferenceStruct), 2, count);
            goto READ_END;
        }
        else
        {
            
            {
               __X = default!;
               __Y = default!;
            }
#if false
            {
               __X = value.@X;
               __Y = value.@Y;
            }
#endif

            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanaged(out __X); if (count == 1) goto SKIP_READ;
            __Y = reader.ReadString(); if (count == 2) goto SKIP_READ;

    SKIP_READ:
            
            {
                goto NEW;
            }
#if false
            {
                goto SET;
            }
#endif
        }

    SET:
        
        value.@X = __X;
        value.@Y = __Y;
        goto READ_END;

    NEW:
        value = new IncludesReferenceStruct()
        {
            @X = __X,
            @Y = __Y
        };

    READ_END:

    END:

        return;
    }
}
partial struct IncludesReferenceStruct
{
    [global::MemoryPack.Internal.Preserve]
    sealed class IncludesReferenceStructFormatter : MemoryPackFormatter<IncludesReferenceStruct>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref IncludesReferenceStruct value)
        {
            IncludesReferenceStruct.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref IncludesReferenceStruct value)
        {
            IncludesReferenceStruct.Deserialize(ref reader, ref value);
        }
    }
}
}
