
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>string</b> MyProperty1<br/>
/// <b>string</b> MyProperty2<br/>
/// </code>
/// </remarks>
partial class ParameterCheck : IMemoryPackable<ParameterCheck>
{

    static partial void StaticConstructor();

    static ParameterCheck()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<ParameterCheck>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new ParameterCheckFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<ParameterCheck[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<ParameterCheck>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref ParameterCheck? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteObjectHeader(2);
        writer.WriteString(value.@MyProperty1);
        writer.WriteString(value.@MyProperty2);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref ParameterCheck? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        string __MyProperty1;
        string __MyProperty2;

        
        if (count == 2)
        {
            if (value == null)
            {
                __MyProperty1 = reader.ReadString();
                __MyProperty2 = reader.ReadString();


                goto NEW;
            }
            else
            {
                __MyProperty1 = value.@MyProperty1;
                __MyProperty2 = value.@MyProperty2;

                __MyProperty1 = reader.ReadString();
                __MyProperty2 = reader.ReadString();

                goto SET;
            }

        }
        else if (count > 2)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(ParameterCheck), 2, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __MyProperty1 = default!;
               __MyProperty2 = default!;
            }
            else
            {
               __MyProperty1 = value.@MyProperty1;
               __MyProperty2 = value.@MyProperty2;
            }


            if (count == 0) goto SKIP_READ;
            __MyProperty1 = reader.ReadString(); if (count == 1) goto SKIP_READ;
            __MyProperty2 = reader.ReadString(); if (count == 2) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        goto NEW;
        // value.@MyProperty1 = __MyProperty1;
        // value.@MyProperty2 = __MyProperty2;
        goto READ_END;

    NEW:
        value = new ParameterCheck(__MyProperty1)
        {
            @MyProperty2 = __MyProperty2
        };

    READ_END:

    END:

        return;
    }
}
partial class ParameterCheck
{
    [global::MemoryPack.Internal.Preserve]
    sealed class ParameterCheckFormatter : MemoryPackFormatter<ParameterCheck>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref ParameterCheck value)
        {
            ParameterCheck.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref ParameterCheck value)
        {
            ParameterCheck.Deserialize(ref reader, ref value);
        }
    }
}
}
