
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>int</b> One<br/>
/// </code>
/// </remarks>
partial class StandardTypeOne : IMemoryPackable<StandardTypeOne>
{

    static partial void StaticConstructor();

    static StandardTypeOne()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<StandardTypeOne>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new StandardTypeOneFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<StandardTypeOne[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<StandardTypeOne>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref StandardTypeOne? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteUnmanagedWithObjectHeader(1, value.@One);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref StandardTypeOne? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        int __One;

        
        if (count == 1)
        {
            if (value == null)
            {
                reader.ReadUnmanaged(out __One);


                goto NEW;
            }
            else
            {
                __One = value.@One;

                reader.ReadUnmanaged(out __One);

                goto SET;
            }

        }
        else if (count > 1)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(StandardTypeOne), 1, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __One = default!;
            }
            else
            {
               __One = value.@One;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanaged(out __One); if (count == 1) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@One = __One;
        goto READ_END;

    NEW:
        value = new StandardTypeOne()
        {
            @One = __One
        };

    READ_END:

    END:

        return;
    }
}
partial class StandardTypeOne
{
    [global::MemoryPack.Internal.Preserve]
    sealed class StandardTypeOneFormatter : MemoryPackFormatter<StandardTypeOne>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref StandardTypeOne value)
        {
            StandardTypeOne.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref StandardTypeOne value)
        {
            StandardTypeOne.Deserialize(ref reader, ref value);
        }
    }
}
}
