
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models.More {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>string</b> One<br/>
/// <b>string</b> Two<br/>
/// </code>
/// </remarks>
partial class StandardTypeTwo : IMemoryPackable<StandardTypeTwo>
{

    static partial void StaticConstructor();

    static StandardTypeTwo()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<StandardTypeTwo>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new StandardTypeTwoFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<StandardTypeTwo[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<StandardTypeTwo>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref StandardTypeTwo? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteObjectHeader(2);
        writer.WriteString(value.@One);
        writer.WriteString(value.@Two);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref StandardTypeTwo? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        string __One;
        string __Two;

        
        if (count == 2)
        {
            if (value == null)
            {
                __One = reader.ReadString();
                __Two = reader.ReadString();


                goto NEW;
            }
            else
            {
                __One = value.@One;
                __Two = value.@Two;

                __One = reader.ReadString();
                __Two = reader.ReadString();

                goto SET;
            }

        }
        else if (count > 2)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(StandardTypeTwo), 2, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __One = default!;
               __Two = default!;
            }
            else
            {
               __One = value.@One;
               __Two = value.@Two;
            }


            if (count == 0) goto SKIP_READ;
            __One = reader.ReadString(); if (count == 1) goto SKIP_READ;
            __Two = reader.ReadString(); if (count == 2) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@One = __One;
        value.@Two = __Two;
        goto READ_END;

    NEW:
        value = new StandardTypeTwo()
        {
            @One = __One,
            @Two = __Two
        };

    READ_END:

    END:

        return;
    }
}
partial class StandardTypeTwo
{
    [global::MemoryPack.Internal.Preserve]
    sealed class StandardTypeTwoFormatter : MemoryPackFormatter<StandardTypeTwo>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref StandardTypeTwo value)
        {
            StandardTypeTwo.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref StandardTypeTwo value)
        {
            StandardTypeTwo.Deserialize(ref reader, ref value);
        }
    }
}
}
