
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>int</b> MyProperty1<br/>
/// <b>MemoryPack.Tests.Models.Overwrite</b> MyProperty2<br/>
/// <b>System.Collections.Generic.List&lt;int&gt;</b> MyProperty3<br/>
/// </code>
/// </remarks>
partial class Overwrite4 : IMemoryPackable<Overwrite4>
{

    static partial void StaticConstructor();

    static Overwrite4()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Overwrite4>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new Overwrite4Formatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Overwrite4[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<Overwrite4>());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<global::System.Collections.Generic.List<int>>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ListFormatter<int>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref Overwrite4? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteUnmanagedWithObjectHeader(3, value.@MyProperty1);
        writer.WritePackable(value.@MyProperty2);
        writer.WriteValue(value.@MyProperty3);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref Overwrite4? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        int __MyProperty1;
        global::MemoryPack.Tests.Models.Overwrite __MyProperty2;
        global::System.Collections.Generic.List<int> __MyProperty3;

        
        if (count == 3)
        {
            if (value == null)
            {
                reader.ReadUnmanaged(out __MyProperty1);
                __MyProperty2 = reader.ReadPackable<global::MemoryPack.Tests.Models.Overwrite>();
                __MyProperty3 = reader.ReadValue<global::System.Collections.Generic.List<int>>();


                goto NEW;
            }
            else
            {
                __MyProperty1 = value.@MyProperty1;
                __MyProperty2 = value.@MyProperty2;
                __MyProperty3 = value.@MyProperty3;

                reader.ReadUnmanaged(out __MyProperty1);
                reader.ReadPackable(ref __MyProperty2);
                reader.ReadValue(ref __MyProperty3);

                goto SET;
            }

        }
        else if (count > 3)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(Overwrite4), 3, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __MyProperty1 = default!;
               __MyProperty2 = default!;
               __MyProperty3 = default!;
            }
            else
            {
               __MyProperty1 = value.@MyProperty1;
               __MyProperty2 = value.@MyProperty2;
               __MyProperty3 = value.@MyProperty3;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanaged(out __MyProperty1); if (count == 1) goto SKIP_READ;
            reader.ReadPackable(ref __MyProperty2); if (count == 2) goto SKIP_READ;
            reader.ReadValue(ref __MyProperty3); if (count == 3) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@MyProperty1 = __MyProperty1;
        value.@MyProperty2 = __MyProperty2;
        value.@MyProperty3 = __MyProperty3;
        goto READ_END;

    NEW:
        value = new Overwrite4()
        {
            @MyProperty1 = __MyProperty1,
            @MyProperty2 = __MyProperty2,
            @MyProperty3 = __MyProperty3
        };

    READ_END:

    END:

        return;
    }
}
partial class Overwrite4
{
    [global::MemoryPack.Internal.Preserve]
    sealed class Overwrite4Formatter : MemoryPackFormatter<Overwrite4>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref Overwrite4 value)
        {
            Overwrite4.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref Overwrite4 value)
        {
            Overwrite4.Deserialize(ref reader, ref value);
        }
    }
}
}
