
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>int</b> X<br/>
/// <b>int</b> Y<br/>
/// </code>
/// </remarks>
partial class ExplicitlyCtor : IMemoryPackable<ExplicitlyCtor>
{

    static partial void StaticConstructor();

    static ExplicitlyCtor()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<ExplicitlyCtor>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new ExplicitlyCtorFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<ExplicitlyCtor[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<ExplicitlyCtor>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref ExplicitlyCtor? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteUnmanagedWithObjectHeader(2, value.@X, value.@Y);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref ExplicitlyCtor? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        int __X;
        int __Y;

        
        if (count == 2)
        {
            if (value == null)
            {
                reader.ReadUnmanaged(out __X, out __Y);


                goto NEW;
            }
            else
            {
                __X = value.@X;
                __Y = value.@Y;

                reader.ReadUnmanaged(out __X);
                reader.ReadUnmanaged(out __Y);

                goto SET;
            }

        }
        else if (count > 2)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(ExplicitlyCtor), 2, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __X = default!;
               __Y = default!;
            }
            else
            {
               __X = value.@X;
               __Y = value.@Y;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanaged(out __X); if (count == 1) goto SKIP_READ;
            reader.ReadUnmanaged(out __Y); if (count == 2) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        goto NEW;
        // value.@Y = __Y;
        goto READ_END;

    NEW:
        value = new ExplicitlyCtor(__X, __Y)
        {

        };

    READ_END:

    END:

        return;
    }
}
partial class ExplicitlyCtor
{
    [global::MemoryPack.Internal.Preserve]
    sealed class ExplicitlyCtorFormatter : MemoryPackFormatter<ExplicitlyCtor>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref ExplicitlyCtor value)
        {
            ExplicitlyCtor.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref ExplicitlyCtor value)
        {
            ExplicitlyCtor.Deserialize(ref reader, ref value);
        }
    }
}
}
