
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>string</b> Before<br/>
/// <b>MemoryPack.Tests.Models.Versioning4</b> V4<br/>
/// <b>string</b> After<br/>
/// </code>
/// </remarks>
partial class WrappedVersioning4 : IMemoryPackable<WrappedVersioning4>
{

    static partial void StaticConstructor();

    static WrappedVersioning4()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<WrappedVersioning4>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new WrappedVersioning4Formatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<WrappedVersioning4[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<WrappedVersioning4>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref WrappedVersioning4? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteObjectHeader(3);
        writer.WriteString(value.@Before);
        writer.WritePackable(value.@V4);
        writer.WriteString(value.@After);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref WrappedVersioning4? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        string __Before;
        global::MemoryPack.Tests.Models.Versioning4 __V4;
        string __After;

        
        if (count == 3)
        {
            if (value == null)
            {
                __Before = reader.ReadString();
                __V4 = reader.ReadPackable<global::MemoryPack.Tests.Models.Versioning4>();
                __After = reader.ReadString();


                goto NEW;
            }
            else
            {
                __Before = value.@Before;
                __V4 = value.@V4;
                __After = value.@After;

                __Before = reader.ReadString();
                reader.ReadPackable(ref __V4);
                __After = reader.ReadString();

                goto SET;
            }

        }
        else if (count > 3)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(WrappedVersioning4), 3, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __Before = default!;
               __V4 = default!;
               __After = default!;
            }
            else
            {
               __Before = value.@Before;
               __V4 = value.@V4;
               __After = value.@After;
            }


            if (count == 0) goto SKIP_READ;
            __Before = reader.ReadString(); if (count == 1) goto SKIP_READ;
            reader.ReadPackable(ref __V4); if (count == 2) goto SKIP_READ;
            __After = reader.ReadString(); if (count == 3) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@Before = __Before;
        value.@V4 = __V4;
        value.@After = __After;
        goto READ_END;

    NEW:
        value = new WrappedVersioning4()
        {
            @Before = __Before,
            @V4 = __V4,
            @After = __After
        };

    READ_END:

    END:

        return;
    }
}
partial class WrappedVersioning4
{
    [global::MemoryPack.Internal.Preserve]
    sealed class WrappedVersioning4Formatter : MemoryPackFormatter<WrappedVersioning4>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref WrappedVersioning4 value)
        {
            WrappedVersioning4.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref WrappedVersioning4 value)
        {
            WrappedVersioning4.Deserialize(ref reader, ref value);
        }
    }
}
}
