
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>int</b> MyProperty<br/>
/// <b>string</b> Bar<br/>
/// </code>
/// </remarks>
partial class Impl2 : IMemoryPackable<Impl2>
{

    static partial void StaticConstructor();

    static Impl2()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Impl2>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new Impl2Formatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Impl2[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<Impl2>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref Impl2? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteUnmanagedWithObjectHeader(2, value.@MyProperty);
        writer.WriteString(value.@Bar);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref Impl2? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        int __MyProperty;
        string __Bar;

        
        if (count == 2)
        {
            if (value == null)
            {
                reader.ReadUnmanaged(out __MyProperty);
                __Bar = reader.ReadString();


                goto NEW;
            }
            else
            {
                __MyProperty = value.@MyProperty;
                __Bar = value.@Bar;

                reader.ReadUnmanaged(out __MyProperty);
                __Bar = reader.ReadString();

                goto SET;
            }

        }
        else if (count > 2)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(Impl2), 2, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __MyProperty = default!;
               __Bar = default!;
            }
            else
            {
               __MyProperty = value.@MyProperty;
               __Bar = value.@Bar;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanaged(out __MyProperty); if (count == 1) goto SKIP_READ;
            __Bar = reader.ReadString(); if (count == 2) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@MyProperty = __MyProperty;
        value.@Bar = __Bar;
        goto READ_END;

    NEW:
        value = new Impl2()
        {
            @MyProperty = __MyProperty,
            @Bar = __Bar
        };

    READ_END:

    END:

        return;
    }
}
partial class Impl2
{
    [global::MemoryPack.Internal.Preserve]
    sealed class Impl2Formatter : MemoryPackFormatter<Impl2>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref Impl2 value)
        {
            Impl2.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref Impl2 value)
        {
            Impl2.Deserialize(ref reader, ref value);
        }
    }
}
}
