
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>T</b> Versioned<br/>
/// <b>int[]</b> Values<br/>
/// </code>
/// </remarks>
partial class VTWrapper<T> : IMemoryPackable<VTWrapper<T>>
{

    static partial void StaticConstructor();

    static VTWrapper()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<VTWrapper<T>>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new VTWrapperFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<VTWrapper<T>[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<VTWrapper<T>>());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<int[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<int>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref VTWrapper<T>? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteObjectHeader(2);
        writer.WriteValue(value.@Versioned);
        writer.WriteUnmanagedArray(value.@Values);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref VTWrapper<T>? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        T __Versioned;
        int[] __Values;

        
        if (count == 2)
        {
            if (value == null)
            {
                __Versioned = reader.ReadValue<T>();
                __Values = reader.ReadUnmanagedArray<int>();


                goto NEW;
            }
            else
            {
                __Versioned = value.@Versioned;
                __Values = value.@Values;

                reader.ReadValue(ref __Versioned);
                reader.ReadUnmanagedArray(ref __Values);

                goto SET;
            }

        }
        else if (count > 2)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(VTWrapper<T>), 2, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __Versioned = default!;
               __Values = default!;
            }
            else
            {
               __Versioned = value.@Versioned;
               __Values = value.@Values;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadValue(ref __Versioned); if (count == 1) goto SKIP_READ;
            reader.ReadUnmanagedArray(ref __Values); if (count == 2) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@Versioned = __Versioned;
        value.@Values = __Values;
        goto READ_END;

    NEW:
        value = new VTWrapper<T>()
        {
            @Versioned = __Versioned,
            @Values = __Values
        };

    READ_END:

    END:

        return;
    }
}
partial class VTWrapper<T>
{
    [global::MemoryPack.Internal.Preserve]
    sealed class VTWrapperFormatter : MemoryPackFormatter<VTWrapper<T>>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref VTWrapper<T> value)
        {
            VTWrapper<T>.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref VTWrapper<T> value)
        {
            VTWrapper<T>.Deserialize(ref reader, ref value);
        }
    }
}
}
