
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>int</b> MyProperty1<br/>
/// <b>int</b> MyProperty2<br/>
/// <b>string</b> MyProperty3<br/>
/// <b>string</b> MyProperty4<br/>
/// </code>
/// </remarks>
partial class Overwrite3 : IMemoryPackable<Overwrite3>
{

    static partial void StaticConstructor();

    static Overwrite3()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Overwrite3>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new Overwrite3Formatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Overwrite3[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<Overwrite3>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref Overwrite3? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteUnmanagedWithObjectHeader(4, value.@MyProperty1, value.@MyProperty2);
        writer.WriteString(value.@MyProperty3);
        writer.WriteString(value.@MyProperty4);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref Overwrite3? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        int __MyProperty1;
        int __MyProperty2;
        string __MyProperty3;
        string __MyProperty4;

        
        if (count == 4)
        {
            if (value == null)
            {
                reader.ReadUnmanaged(out __MyProperty1, out __MyProperty2);
                __MyProperty3 = reader.ReadString();
                __MyProperty4 = reader.ReadString();


                goto NEW;
            }
            else
            {
                __MyProperty1 = value.@MyProperty1;
                __MyProperty2 = value.@MyProperty2;
                __MyProperty3 = value.@MyProperty3;
                __MyProperty4 = value.@MyProperty4;

                reader.ReadUnmanaged(out __MyProperty1);
                reader.ReadUnmanaged(out __MyProperty2);
                __MyProperty3 = reader.ReadString();
                __MyProperty4 = reader.ReadString();

                goto SET;
            }

        }
        else if (count > 4)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(Overwrite3), 4, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __MyProperty1 = default!;
               __MyProperty2 = default!;
               __MyProperty3 = default!;
               __MyProperty4 = default!;
            }
            else
            {
               __MyProperty1 = value.@MyProperty1;
               __MyProperty2 = value.@MyProperty2;
               __MyProperty3 = value.@MyProperty3;
               __MyProperty4 = value.@MyProperty4;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanaged(out __MyProperty1); if (count == 1) goto SKIP_READ;
            reader.ReadUnmanaged(out __MyProperty2); if (count == 2) goto SKIP_READ;
            __MyProperty3 = reader.ReadString(); if (count == 3) goto SKIP_READ;
            __MyProperty4 = reader.ReadString(); if (count == 4) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        goto NEW;
        // value.@MyProperty1 = __MyProperty1;
        // value.@MyProperty2 = __MyProperty2;
        // value.@MyProperty3 = __MyProperty3;
        // value.@MyProperty4 = __MyProperty4;
        goto READ_END;

    NEW:
        value = new Overwrite3(__MyProperty1, __MyProperty2)
        {
            @MyProperty3 = __MyProperty3,
            @MyProperty4 = __MyProperty4
        };

    READ_END:

    END:

        return;
    }
}
partial class Overwrite3
{
    [global::MemoryPack.Internal.Preserve]
    sealed class Overwrite3Formatter : MemoryPackFormatter<Overwrite3>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref Overwrite3 value)
        {
            Overwrite3.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref Overwrite3 value)
        {
            Overwrite3.Deserialize(ref reader, ref value);
        }
    }
}
}
