
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>int</b> Int<br/>
/// <b>double</b> Double<br/>
/// <b>string</b> String<br/>
/// </code>
/// </remarks>
partial class Inner : IMemoryPackable<Inner>
{

    static partial void StaticConstructor();

    static Inner()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Inner>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new InnerFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<Inner[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<Inner>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref Inner? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteUnmanagedWithObjectHeader(3, value.@Int, value.@Double);
        writer.WriteString(value.@String);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref Inner? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        int __Int;
        double __Double;
        string __String;

        
        if (count == 3)
        {
            if (value == null)
            {
                reader.ReadUnmanaged(out __Int, out __Double);
                __String = reader.ReadString();


                goto NEW;
            }
            else
            {
                __Int = value.@Int;
                __Double = value.@Double;
                __String = value.@String;

                reader.ReadUnmanaged(out __Int);
                reader.ReadUnmanaged(out __Double);
                __String = reader.ReadString();

                goto SET;
            }

        }
        else if (count > 3)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(Inner), 3, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __Int = default!;
               __Double = default!;
               __String = default!;
            }
            else
            {
               __Int = value.@Int;
               __Double = value.@Double;
               __String = value.@String;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadUnmanaged(out __Int); if (count == 1) goto SKIP_READ;
            reader.ReadUnmanaged(out __Double); if (count == 2) goto SKIP_READ;
            __String = reader.ReadString(); if (count == 3) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@Int = __Int;
        value.@Double = __Double;
        value.@String = __String;
        goto READ_END;

    NEW:
        value = new Inner()
        {
            @Int = __Int,
            @Double = __Double,
            @String = __String
        };

    READ_END:

    END:

        return;
    }
}
partial class Inner
{
    [global::MemoryPack.Internal.Preserve]
    sealed class InnerFormatter : MemoryPackFormatter<Inner>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref Inner value)
        {
            Inner.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref Inner value)
        {
            Inner.Deserialize(ref reader, ref value);
        }
    }
}
}
