
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>T</b> Value<br/>
/// <b>int</b> MyProperty<br/>
/// </code>
/// </remarks>
partial class GenricUnionA<T> : IMemoryPackable<GenricUnionA<T>>
{

    static partial void StaticConstructor();

    static GenricUnionA()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<GenricUnionA<T>>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new GenricUnionAFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<GenricUnionA<T>[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<GenricUnionA<T>>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref GenricUnionA<T>? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteObjectHeader(2);
        writer.WriteValue(value.@Value);
        writer.WriteUnmanaged(value.@MyProperty);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref GenricUnionA<T>? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        T __Value;
        int __MyProperty;

        
        if (count == 2)
        {
            if (value == null)
            {
                __Value = reader.ReadValue<T>();
                reader.ReadUnmanaged(out __MyProperty);


                goto NEW;
            }
            else
            {
                __Value = value.@Value;
                __MyProperty = value.@MyProperty;

                reader.ReadValue(ref __Value);
                reader.ReadUnmanaged(out __MyProperty);

                goto SET;
            }

        }
        else if (count > 2)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(GenricUnionA<T>), 2, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __Value = default!;
               __MyProperty = default!;
            }
            else
            {
               __Value = value.@Value;
               __MyProperty = value.@MyProperty;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadValue(ref __Value); if (count == 1) goto SKIP_READ;
            reader.ReadUnmanaged(out __MyProperty); if (count == 2) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@Value = __Value;
        value.@MyProperty = __MyProperty;
        goto READ_END;

    NEW:
        value = new GenricUnionA<T>()
        {
            @Value = __Value,
            @MyProperty = __MyProperty
        };

    READ_END:

    END:

        return;
    }
}
partial class GenricUnionA<T>
{
    [global::MemoryPack.Internal.Preserve]
    sealed class GenricUnionAFormatter : MemoryPackFormatter<GenricUnionA<T>>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref GenricUnionA<T> value)
        {
            GenricUnionA<T>.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref GenricUnionA<T> value)
        {
            GenricUnionA<T>.Deserialize(ref reader, ref value);
        }
    }
}
}
