
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>string</b> MyProperty<br/>
/// </code>
/// </remarks>
partial struct StructWithConstructor1 : IMemoryPackable<StructWithConstructor1>
{

    static partial void StaticConstructor();

    static StructWithConstructor1()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<StructWithConstructor1>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new StructWithConstructor1Formatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<StructWithConstructor1[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<StructWithConstructor1>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref StructWithConstructor1 value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {



        writer.WriteObjectHeader(1);
        writer.WriteString(value.@MyProperty);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref StructWithConstructor1 value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        string __MyProperty;

        
        if (count == 1)
        {
            
            {
                __MyProperty = reader.ReadString();


                goto NEW;
            }
#if false
            {
                __MyProperty = value.@MyProperty;

                __MyProperty = reader.ReadString();

                goto SET;
            }
#endif
        }
        else if (count > 1)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(StructWithConstructor1), 1, count);
            goto READ_END;
        }
        else
        {
            
            {
               __MyProperty = default!;
            }
#if false
            {
               __MyProperty = value.@MyProperty;
            }
#endif

            if (count == 0) goto SKIP_READ;
            __MyProperty = reader.ReadString(); if (count == 1) goto SKIP_READ;

    SKIP_READ:
            
            {
                goto NEW;
            }
#if false
            {
                goto SET;
            }
#endif
        }

    SET:
        goto NEW;
        // value.@MyProperty = __MyProperty;
        goto READ_END;

    NEW:
        value = new StructWithConstructor1(__MyProperty)
        {

        };

    READ_END:

    END:

        return;
    }
}
partial struct StructWithConstructor1
{
    [global::MemoryPack.Internal.Preserve]
    sealed class StructWithConstructor1Formatter : MemoryPackFormatter<StructWithConstructor1>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref StructWithConstructor1 value)
        {
            StructWithConstructor1.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref StructWithConstructor1 value)
        {
            StructWithConstructor1.Deserialize(ref reader, ref value);
        }
    }
}
}
