
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace MemoryPack.Tests.Models {


partial interface IUnionInterface : IMemoryPackFormatterRegister
{
    static partial void StaticConstructor();

    static IUnionInterface()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<IUnionInterface>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new IUnionInterfaceFormatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<IUnionInterface[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<IUnionInterface>());
        }
    }

    [global::MemoryPack.Internal.Preserve]
    sealed class IUnionInterfaceFormatter : MemoryPackFormatter<IUnionInterface>
    {
        static readonly System.Collections.Generic.Dictionary<Type, ushort> __typeToTag = new(2)
        {
            { typeof(global::MemoryPack.Tests.Models.Impl1), 0 },
            { typeof(global::MemoryPack.Tests.Models.Impl2), 1 },
        };

        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref IUnionInterface? value)
        {

            if (value == null)
            {
                writer.WriteNullUnionHeader();

                return;
            }

            if (__typeToTag.TryGetValue(value.GetType(), out var tag))
            {
                writer.WriteUnionHeader(tag);

                switch (tag)
                {
                    case 0: writer.WritePackable(System.Runtime.CompilerServices.Unsafe.As<global::MemoryPack.Tests.Models.IUnionInterface?, global::MemoryPack.Tests.Models.Impl1>(ref value)); break;
                    case 1: writer.WritePackable(System.Runtime.CompilerServices.Unsafe.As<global::MemoryPack.Tests.Models.IUnionInterface?, global::MemoryPack.Tests.Models.Impl2>(ref value)); break;
                    default:
                        break;
                }
            }
            else
            {
                MemoryPackSerializationException.ThrowNotFoundInUnionType(value.GetType(), typeof(global::MemoryPack.Tests.Models.IUnionInterface));
            }

        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref IUnionInterface? value)
        {

            if (!reader.TryReadUnionHeader(out var tag))
            {
                value = default;

                return;
            }

            switch (tag)
            {
                case 0:
                    if (value is global::MemoryPack.Tests.Models.Impl1)
                    {
                        reader.ReadPackable(ref System.Runtime.CompilerServices.Unsafe.As<global::MemoryPack.Tests.Models.IUnionInterface?, global::MemoryPack.Tests.Models.Impl1>(ref value));
                    }
                    else
                    {
                        value = (global::MemoryPack.Tests.Models.Impl1)reader.ReadPackable<global::MemoryPack.Tests.Models.Impl1>();
                    }
                    break;
                case 1:
                    if (value is global::MemoryPack.Tests.Models.Impl2)
                    {
                        reader.ReadPackable(ref System.Runtime.CompilerServices.Unsafe.As<global::MemoryPack.Tests.Models.IUnionInterface?, global::MemoryPack.Tests.Models.Impl2>(ref value));
                    }
                    else
                    {
                        value = (global::MemoryPack.Tests.Models.Impl2)reader.ReadPackable<global::MemoryPack.Tests.Models.Impl2>();
                    }
                    break;
                default:
                    MemoryPackSerializationException.ThrowInvalidTag(tag, typeof(global::MemoryPack.Tests.Models.IUnionInterface));
                    break;
            }

        }
    }
}
}
