
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using MemoryPack;

namespace Models {

/// <remarks>
/// MemoryPack GenerateType: Object<br/>
/// <code>
/// <b>System.Collections.Generic.HashSet&lt;long&gt;</b> Set<br/>
/// </code>
/// </remarks>
partial class MyContainer3 : IMemoryPackable<MyContainer3>
{

    static partial void StaticConstructor();

    static MyContainer3()
    {
        RegisterFormatter();
        StaticConstructor();
    }

    [global::MemoryPack.Internal.Preserve]
    public static void RegisterFormatter()
    {
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<MyContainer3>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new MyContainer3Formatter());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<MyContainer3[]>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.ArrayFormatter<MyContainer3>());
        }
        if (!global::MemoryPack.MemoryPackFormatterProvider.IsRegistered<global::System.Collections.Generic.HashSet<long>>())
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MemoryPack.Formatters.HashSetFormatter<long>());
        }

    }

    [global::MemoryPack.Internal.Preserve]
    public static void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, ref MyContainer3? value) where TBufferWriter : class, System.Buffers.IBufferWriter<byte>
    {

        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }

        writer.WriteObjectHeader(1);
        writer.WriteValue(value.@Set);

    END:

        return;
    }

    [global::MemoryPack.Internal.Preserve]
    public static void Deserialize(ref MemoryPackReader reader, ref MyContainer3? value)
    {

        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }



        global::System.Collections.Generic.HashSet<long> __Set;

        
        if (count == 1)
        {
            if (value == null)
            {
                __Set = reader.ReadValue<global::System.Collections.Generic.HashSet<long>>();


                goto NEW;
            }
            else
            {
                __Set = value.@Set;

                reader.ReadValue(ref __Set);

                goto SET;
            }

        }
        else if (count > 1)
        {
            MemoryPackSerializationException.ThrowInvalidPropertyCount(typeof(MyContainer3), 1, count);
            goto READ_END;
        }
        else
        {
            if (value == null)
            {
               __Set = default!;
            }
            else
            {
               __Set = value.@Set;
            }


            if (count == 0) goto SKIP_READ;
            reader.ReadValue(ref __Set); if (count == 1) goto SKIP_READ;

    SKIP_READ:
            if (value == null)
            {
                goto NEW;
            }
            else
            {
                goto SET;
            }

        }

    SET:
        
        value.@Set = __Set;
        goto READ_END;

    NEW:
        value = new MyContainer3()
        {
            @Set = __Set
        };

    READ_END:

    END:

        return;
    }
}
partial class MyContainer3
{
    [global::MemoryPack.Internal.Preserve]
    sealed class MyContainer3Formatter : MemoryPackFormatter<MyContainer3>
    {
        [global::MemoryPack.Internal.Preserve]
        public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer,  ref MyContainer3 value)
        {
            MyContainer3.Serialize(ref writer, ref value);
        }

        [global::MemoryPack.Internal.Preserve]
        public override void Deserialize(ref MemoryPackReader reader, ref MyContainer3 value)
        {
            MyContainer3.Deserialize(ref reader, ref value);
        }
    }
}
}
